sudo: false

language:
  - cpp
compiler:
  - gcc
addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test

before_install:
  - pip install --user cpp-coveralls
    # Combine global build options with OS/compiler-dependent options
    - export CMAKE_OPTIONS=${CMAKE_OPTIONS}" "${ENV_CMAKE_OPTIONS}
    - export CXX_FLAGS=${CXX_FLAGS}" "${ENV_CXX_FLAGS}
script:
  - mkdir build
  - cd build
  - cmake .. -DXWIN_OS=NOOP -DXWIN_TESTS=ON ${CMAKE_OPTIONS} -DCMAKE_CXX_FLAGS=${CXX_FLAGS} -DCMAKE_BUILD_TYPE=Coverage
  - ctest

after_success:
  - coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*tests/.*.cpp.*"

notifications:
  email: false