sudo: false
env:
  global:
    - CXX_FLAGS="-Wall -pedantic -Werror -Wno-variadic-macros -Wno-long-long -Wno-shadow"
language:
  - cpp
compiler:
  - gcc
addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test

before_install:
  - pip install --user cpp-coveralls
  - export CXX_FLAGS=${CXX_FLAGS}" "${ENV_CXX_FLAGS}
script:
  - mkdir build
  - cd build
  - cmake .. -DXWIN_OS=NOOP -DXWIN_TESTS=ON

after_success:
  - coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*tests/.*.cpp.*"

notifications:
  email: false