sudo: false

language:
  - cpp
compiler:
  - clang
addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test

before_install:
  - pip install --user cpp-coveralls

script:
  - mkdir build
  - cd build
  - cmake .. -DXWIN_OS=NOOP -DXWIN_TESTS=ON
  - make
  - ./Tests

after_success:
  - coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*tests/.*.cpp.*"

notifications:
  email: false